import type { Product } from "@/lib/data"
import { artisans } from "@/lib/data"

export const shopCategories = [
  "Cups and plates",
  "Show Pieces",
  "Masks",
  "Carpets",
  "Necklaces",
  "Others",
] as const

const categoryAliasMap: Record<string, (typeof shopCategories)[number]> = {
  "cups-and-plates": "Cups and plates",
  cupsandplates: "Cups and plates",
  cups: "Cups and plates",
  plates: "Cups and plates",
  "show-pieces": "Show Pieces",
  showpieces: "Show Pieces",
  showpiece: "Show Pieces",
  masks: "Masks",
  mask: "Masks",
  carpets: "Carpets",
  carpet: "Carpets",
  necklaces: "Necklaces",
  necklace: "Necklaces",
  bracelets: "Necklaces",
  bracelet: "Necklaces",
  others: "Others",
  other: "Others",
  ritual: "Cups and plates",
}

function slugify(value: string) {
  return value.trim().toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")
}

export function normalizeShopCategory(value?: string | null) {
  if (!value) return null

  const normalized = slugify(value)
  if (normalized === "all" || normalized === "all-categories") return null
  if (normalized in categoryAliasMap) {
    return categoryAliasMap[normalized]
  }

  return shopCategories.find((category) => slugify(category) === normalized) ?? null
}

export const shopProducts: Product[] = [
  {
    id: "sp001",
    name: "Imperial Dragon Motif Teacup",
    slug: "imperial-dragon-motif-teacup",
    price: 1800,
    currency: "INR",
    image: "/images/Shop/Product 1.png",
    images: ["/images/Shop/Product 1.png", "/images/Shop/Product 1 Hover.png"],
    category: "Cups and plates",
    collection: "Table Rituals",
    description: "A hand-finished porcelain teacup inspired by monastery tableware, detailed with a dragon motif that echoes protective Himalayan symbolism.",
    details: [
      "Hand-finished decorative surface",
      "Inspired by monastery table settings",
      "Crafted for display or ceremonial tea service",
      "Packaged in a protective gift box",
    ],
    dimensions: "9cm diameter x 7cm height",
    material: "Porcelain with painted finish",
    origin: "Tawang District",
    artisan: artisans[0],
    inStock: true,
    isLimited: false,
  },
  {
    id: "sp002",
    name: "Ritual Gilded Butter Lamp Cup",
    slug: "ritual-gilded-butter-lamp-cup",
    price: 4200,
    currency: "INR",
    image: "/images/Shop/Product 2.png",
    images: ["/images/Shop/Product 2.png", "/images/Shop/Product 2 Hover.png"],
    category: "Cups and plates",
    collection: "Table Rituals",
    description: "A luminous butter lamp cup with a warm gilt finish, created as a collectible object for intimate altars and layered tablescapes.",
    details: [
      "Reflective metallic finish",
      "Designed for shelf styling and ritual corners",
      "Balanced footed silhouette",
      "Comes with care instructions",
    ],
    dimensions: "11cm diameter x 8cm height",
    material: "Metal alloy with gilded finish",
    origin: "West Kameng District",
    artisan: artisans[1],
    inStock: true,
    isLimited: true,
    edition: "Collector Series - 5 of 20",
  },
  {
    id: "sp003",
    name: "Ornate Floral Ritual Bowl",
    slug: "ornate-floral-ritual-bowl",
    price: 5400,
    currency: "INR",
    image: "/images/Shop/Product 3.png",
    images: ["/images/Shop/Product 3.png", "/images/Shop/Product 3 Hover.png"],
    category: "Cups and plates",
    collection: "Table Rituals",
    description: "A richly ornamented bowl designed for festive tables and ritual display, combining floral detailing with a polished ceremonial presence.",
    details: [
      "Decorative floral patterning",
      "Rounded profile for serving or display",
      "Hand-polished finish",
      "Suitable for dry decorative use",
    ],
    dimensions: "18cm diameter x 7cm height",
    material: "Decorative metal alloy",
    origin: "Tawang District",
    artisan: artisans[1],
    inStock: true,
    isLimited: false,
  },
  {
    id: "sp004",
    name: "Majestic Ritual Soul Mask",
    slug: "majestic-ritual-soul-mask",
    price: 12400,
    currency: "INR",
    image: "/images/Shop/Product 4.png",
    images: ["/images/Shop/Product 4.png", "/images/Shop/Product 4 Hover.png"],
    category: "Masks",
    collection: "Spirit and Form",
    description: "A dramatic wall-ready mask with layered features and saturated pigments, created as a statement piece rooted in ceremonial visual language.",
    details: [
      "Wall display ready",
      "Hand-painted surface accents",
      "Expressive carved features",
      "Protective storage wrapping included",
    ],
    dimensions: "34cm x 22cm x 12cm",
    material: "Carved wood with painted finish",
    origin: "West Siang District",
    artisan: artisans[2],
    inStock: true,
    isLimited: true,
    edition: "Studio Piece - 2 of 8",
  },
  {
    id: "sp005",
    name: "Ancient Green Deity Mask",
    slug: "ancient-green-deity-mask",
    price: 4500,
    currency: "INR",
    image: "/images/Shop/Product 5.png",
    images: ["/images/Shop/Product 5.png", "/images/Shop/Product 5 Hover.png"],
    category: "Masks",
    collection: "Spirit and Form",
    description: "A compact ceremonial mask finished in deep green tones, ideal for gallery walls and layered heritage interiors.",
    details: [
      "Compact wall format",
      "Painterly green and gold detailing",
      "Display hook attached on reverse",
      "Pairs well with grouped wall installations",
    ],
    dimensions: "28cm x 18cm x 10cm",
    material: "Wood composite with painted finish",
    origin: "East Siang District",
    artisan: artisans[2],
    inStock: true,
    isLimited: false,
  },
  {
    id: "sp006",
    name: "Serene Buddha Head Sculpture",
    slug: "serene-buddha-head-sculpture",
    price: 9400,
    currency: "INR",
    image: "/images/Shop/Product 6.png",
    images: ["/images/Shop/Product 6.png", "/images/Shop/Product 6 Hover.png"],
    category: "Show Pieces",
    collection: "Sacred Display",
    description: "A contemplative sculpture with quiet surface texture and balanced proportions, suited for consoles, shelves, and meditative corners.",
    details: [
      "Display sculpture with stable base",
      "Weathered hand-finished texture",
      "Made for indoor styling",
      "Packed in foam-lined protective casing",
    ],
    dimensions: "31cm height x 20cm width",
    material: "Resin stone composite",
    origin: "Tawang District",
    artisan: artisans[0],
    inStock: true,
    isLimited: true,
    edition: "Signature Edition - 4 of 15",
  },
  {
    id: "sp007",
    name: "Sacred Geometric Steel Tongue Drum",
    slug: "sacred-geometric-steel-tongue-drum",
    price: 6800,
    currency: "INR",
    image: "/images/Shop/Product 7.png",
    images: ["/images/Shop/Product 7.png", "/images/Shop/Product 7 hover.png"],
    category: "Show Pieces",
    collection: "Sacred Display",
    description: "A sculptural steel tongue drum with geometric surface engraving, curated as both a visual object and a reflective sound instrument.",
    details: [
      "Geometric engraved top surface",
      "Can be used as a decorative instrument",
      "Compact display footprint",
      "Soft storage pouch included",
    ],
    dimensions: "25cm diameter x 13cm height",
    material: "Tuned steel",
    origin: "Papum Pare District",
    artisan: artisans[1],
    inStock: true,
    isLimited: false,
  },
  {
    id: "sp008",
    name: "Sun Guardian Shield Sculpture",
    slug: "sun-guardian-shield-sculpture",
    price: 8500,
    currency: "INR",
    image: "/images/Shop/Product 8.png",
    images: ["/images/Shop/Product 8.png", "/images/Shop/Product 8 Hover.png"],
    category: "Show Pieces",
    collection: "Sacred Display",
    description: "A bold shield-inspired sculpture with a sunburst center, designed to anchor statement walls and curated heritage displays.",
    details: [
      "Statement wall decor format",
      "Raised central medallion",
      "Hand-finished surface variation",
      "Ready for hanging or easel display",
    ],
    dimensions: "36cm diameter x 6cm depth",
    material: "Wood and mixed media finish",
    origin: "Lower Subansiri District",
    artisan: artisans[2],
    inStock: true,
    isLimited: false,
  },
  {
    id: "sp009",
    name: "Monpa Meditation Carpet",
    slug: "monpa-meditation-carpet-shop",
    price: 12800,
    currency: "INR",
    image: "/images/Shop/Product 9.png",
    images: ["/images/Shop/Product 9.png", "/images/Shop/Product 9 Hover.png"],
    category: "Carpets",
    collection: "Woven Ground",
    description: "A richly patterned carpet with a grounded, monastic palette, designed to bring warmth and craft depth to small seating areas and studies.",
    details: [
      "Textured woven surface",
      "Decorative floor or wall use",
      "Patterned border framing",
      "Rolled shipping for flat settling",
    ],
    dimensions: "150cm x 90cm",
    material: "Wool blend textile",
    origin: "Tawang District",
    artisan: artisans[0],
    inStock: true,
    isLimited: true,
    edition: "Loom Batch - 3 of 10",
  },
  {
    id: "sp010",
    name: "Tribal Red Bead Necklace",
    slug: "tribal-red-bead-necklace-shop",
    price: 9200,
    currency: "INR",
    image: "/images/Shop/Product 10.png",
    images: ["/images/Shop/Product 10.png", "/images/Shop/Product 10 Hover.png"],
    category: "Necklaces",
    collection: "Adornment Heritage",
    description: "A vibrant red bead necklace composed for ceremonial presence, balancing bold color with a heritage-inspired layered silhouette.",
    details: [
      "Layered statement necklace",
      "Rich red bead composition",
      "Lightweight for display or styling",
      "Presented in a fabric pouch",
    ],
    dimensions: "Adjustable 46cm to 54cm drop",
    material: "Glass beads and mixed metal findings",
    origin: "East Kameng District",
    artisan: artisans[0],
    inStock: true,
    isLimited: false,
  },
  {
    id: "sp011",
    name: "Imperial Coral Prayer Necklace",
    slug: "imperial-coral-prayer-necklace",
    price: 10800,
    currency: "INR",
    image: "/images/Shop/Product 11.png",
    images: ["/images/Shop/Product 11.png", "/images/Shop/Product 11 Hover.png"],
    category: "Necklaces",
    collection: "Adornment Heritage",
    description: "A ceremonial necklace with coral-toned beads and metallic accents, curated as a luxurious heirloom-inspired accessory.",
    details: [
      "Coral-toned statement beads",
      "Textured accent spacers",
      "Designed for occasion styling",
      "Storage pouch included",
    ],
    dimensions: "Adjustable 44cm to 52cm drop",
    material: "Resin beads and metal spacers",
    origin: "West Siang District",
    artisan: artisans[1],
    inStock: false,
    isLimited: true,
    edition: "Private Release - 1 of 6",
  },
  {
    id: "sp012",
    name: "Sacred Tawang Monastery Banner",
    slug: "sacred-tawang-monastery-banner",
    price: 3600,
    currency: "INR",
    image: "/images/Shop/Product 12.png",
    images: ["/images/Shop/Product 12.png", "/images/Shop/Product 12 Hover.png"],
    category: "Others",
    collection: "Living Rituals",
    description: "A decorative textile banner with sacred color blocking and monastery-inspired motifs, ideal for layering into niche walls and reading rooms.",
    details: [
      "Soft hanging textile format",
      "Monastery-inspired color palette",
      "Lightweight wall display piece",
      "Ships folded in protective wrap",
    ],
    dimensions: "92cm x 38cm",
    material: "Woven textile with tassel trim",
    origin: "Tawang District",
    artisan: artisans[2],
    inStock: true,
    isLimited: false,
  },
]